const mockData = {
  users: [
    {
      id: 'admin_id',
      email: 'admin@recruitai.com',
      password: 'password123',
      role: 'admin',
      token: 'mock_admin_token',
    },
    {
      id: 'recruiter_id',
      email: 'recruiter@recruitai.com',
      password: 'password123',
      role: 'recruiter',
      token: 'mock_recruiter_token',
    },
    {
      id: 'candidate_id',
      email: 'candidate@recruitai.com',
      password: 'password123',
      role: 'candidate',
      token: 'mock_candidate_token',
    },
  ],
  jobs: [
    {
      id: 'job1',
      title: 'Senior Software Engineer',
      description: 'We are looking for a passionate Senior Software Engineer to join our team. You will be responsible for developing and maintaining high-quality software solutions.',
      skills: ['Python', 'Django', 'React', 'AWS', 'SQL'],
      location: 'Remote',
      salary: '120,000 - 150,000 USD',
      status: 'Open',
      applicants: 15,
      matched_candidates: 10,
    },
    {
      id: 'job2',
      title: 'Frontend Developer',
      description: 'Join our dynamic team as a Frontend Developer and build amazing user interfaces using modern web technologies.',
      skills: ['React', 'JavaScript', 'HTML', 'CSS', 'TypeScript'],
      location: 'New York, NY',
      salary: '90,000 - 110,000 USD',
      status: 'Open',
      applicants: 20,
      matched_candidates: 12,
    },
    {
      id: 'job3',
      title: 'DevOps Engineer',
      description: 'We need an experienced DevOps Engineer to streamline our development and operations processes.',
      skills: ['Docker', 'Kubernetes', 'CI/CD', 'Ansible', 'Linux'],
      location: 'San Francisco, CA',
      salary: '130,000 - 160,000 USD',
      status: 'Open',
      applicants: 12,
      matched_candidates: 8,
    },
    {
      id: 'job4',
      title: 'Data Scientist',
      description: 'As a Data Scientist, you will be responsible for analyzing large datasets and building predictive models.',
      skills: ['Python', 'R', 'Machine Learning', 'SQL', ' estadística'],
      location: 'Boston, MA',
      salary: '110,000 - 140,000 USD',
      status: 'Closed',
      applicants: 8,
      matched_candidates: 5,
    },
    {
      id: 'job5',
      title: 'UI/UX Designer',
      description: 'Create intuitive and visually appealing user interfaces for our web and mobile applications.',
      skills: ['Figma', 'Sketch', 'Adobe XD', 'User Research', 'Prototyping'],
      location: 'Remote',
      salary: '80,000 - 100,000 USD',
      status: 'Open',
      applicants: 18,
      matched_candidates: 11,
    },
  ],
  resumes: [
    {
      id: 'resume1',
      name: 'Alice Smith',
      email: 'alice.smith@example.com',
      skills: ['Python', 'Django', 'AWS', 'SQL', 'JavaScript'],
      experience: '5 years',
      education: 'Master of Computer Science',
      match_score: 92,
      job_id: 'job1',
    },
    {
      id: 'resume2',
      name: 'Bob Johnson',
      email: 'bob.johnson@example.com',
      skills: ['React', 'TypeScript', 'HTML', 'CSS', 'Node.js'],
      experience: '3 years',
      education: 'Bachelor of Software Engineering',
      match_score: 88,
      job_id: 'job2',
    },
    {
      id: 'resume3',
      name: 'Charlie Brown',
      email: 'charlie.brown@example.com',
      skills: ['Docker', 'Kubernetes', 'CI/CD', 'Ansible', 'Linux'],
      experience: '7 years',
      education: 'PhD in Computer Science',
      match_score: 95,
      job_id: 'job3',
    },
    {
      id: 'resume4',
      name: 'Diana Prince',
      email: 'diana.prince@example.com',
      skills: ['Python', 'Machine Learning', 'R', 'SQL', 'Data Visualization'],
      experience: '4 years',
      education: 'Master of Data Science',
      match_score: 70,
      job_id: 'job4',
    },
    {
      id: 'resume5',
      name: 'Eve Adams',
      email: 'eve.adams@example.com',
      skills: ['Figma', 'User Research', 'Prototyping', 'Sketch', 'Adobe XD'],
      experience: '2 years',
      education: 'Bachelor of Graphic Design',
      match_score: 85,
      job_id: 'job5',
    },
  ],
  dashboardStats: {
    totalJobs: 5,
    totalCandidates: 5,
    totalResumes: 5,
    totalInterviews: 0,
    openJobs: 4,
    closedJobs: 1,
  },
};

export default mockData;


